image: gradle:8.7-jdk21

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - code_quality
  - test

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build/reports/tests/test

code_quality:
  stage: code_quality
  script:
    - gradle javadoc
    - gradle checkstyleMain
    - gradle checkstyleTest
    - gradle spotlessApply
    - gradle spotlessCheck
  artifacts:
    paths:
      - build/docs/javadoc
      - build/reports/checkstyle
      - build/reports/spotless
    expire_in: 2 weeks
